# Site settings
title: Magpie - Medieval Smuggling
email: TheRavenNevermore@web.de
description: >
  Magpie is a light RPG in 2D top-down perspective, that tells the story of a
  good-for-nothing thief in a medieval fantasy world where alcohol smuggeling
  gangs are becoming big and struggle for power over each over as well as the
  county.
baseurl: "/magpie-game" # the subpath of your site, e.g. /blog/
url: "http://dragons-and-bytecode.github.io" # the base hostname & protocol for your site
twitter_username: hr_rabe
github_username:  dragons-and-bytecode

# Build settings
markdown: kramdown
